FROM node:20-alpine

# Set working directory
WORKDIR /app

# Install dependencies first
COPY package*.json ./
RUN npm install

# Copy rest of the app
COPY . .

# React runs on port 3000
EXPOSE 3000

# Start the React app
CMD ["npm", "start"]
